In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('swiss1.txt',delimiter='')

In [3]:
data

array([[214.8, 131. , 131.1,   9. ,   9.7, 141. ],
       [214.6, 129.7, 129.7,   8.1,   9.5, 141.7],
       [214.8, 129.7, 129.7,   8.7,   9.6, 142.2],
       [214.8, 129.7, 129.6,   7.5,  10.4, 142. ],
       [215. , 129.6, 129.7,  10.4,   7.7, 141.8],
       [215.7, 130.8, 130.5,   9. ,  10.1, 141.4],
       [215.5, 129.5, 129.7,   7.9,   9.6, 141.6],
       [214.5, 129.6, 129.2,   7.2,  10.7, 141.7],
       [214.9, 129.4, 129.7,   8.2,  11. , 141.9],
       [215.2, 130.4, 130.3,   9.2,  10. , 140.7],
       [215.3, 130.4, 130.3,   7.9,  11.7, 141.8],
       [215.1, 129.5, 129.6,   7.7,  10.5, 142.2],
       [215.2, 130.8, 129.6,   7.9,  10.8, 141.4],
       [214.7, 129.7, 129.7,   7.7,  10.9, 141.7],
       [215.1, 129.9, 129.7,   7.7,  10.8, 141.8],
       [214.5, 129.8, 129.8,   9.3,   8.5, 141.6],
       [214.6, 129.9, 130.1,   8.2,   9.8, 141.7],
       [215. , 129.9, 129.7,   9. ,   9. , 141.9],
       [215.2, 129.6, 129.6,   7.4,  11.5, 141.5],
       [214.7, 130.2, 129.9,   

In [4]:
labels = data[:,4]

In [5]:
labels

array([ 9.7,  9.5,  9.6, 10.4,  7.7, 10.1,  9.6, 10.7, 11. , 10. , 11.7,
       10.5, 10.8, 10.9, 10.8,  8.5,  9.8,  9. , 11.5, 10. , 10. , 10.3,
       10.8, 10. , 10.8, 11. ,  9.8,  9.5, 10.5,  9. , 10.7,  9.1, 10.5,
       10.3, 10.6,  9.7,  9.7, 10. ,  9.3,  9.7,  9.4,  9.9,  9. ,  9.8,
       10.2, 10.2, 10.2, 10.9, 10.3,  9.8, 10. ,  9.7, 10.9, 10.9, 10. ,
        9.4, 10.4,  9. , 11. , 10.3,  9.9, 10.5, 10.6, 10.8, 10.6, 10.6,
       10.3,  9.5,  9.8, 11.2, 11.1, 10.3, 10. , 10.5, 10.6, 10.7, 10. ,
       10.6, 10.9, 10. , 10.3, 10.3,  9.7, 10.8, 11.1, 10.2,  9.5, 10.2,
       11.2, 10.5,  9.6,  9.7,  9.9, 10.7, 10. ,  9.5, 10.2, 10.3, 10.2,
       10. ])

In [6]:
features = data[:,4]

In [7]:
features

array([ 9.7,  9.5,  9.6, 10.4,  7.7, 10.1,  9.6, 10.7, 11. , 10. , 11.7,
       10.5, 10.8, 10.9, 10.8,  8.5,  9.8,  9. , 11.5, 10. , 10. , 10.3,
       10.8, 10. , 10.8, 11. ,  9.8,  9.5, 10.5,  9. , 10.7,  9.1, 10.5,
       10.3, 10.6,  9.7,  9.7, 10. ,  9.3,  9.7,  9.4,  9.9,  9. ,  9.8,
       10.2, 10.2, 10.2, 10.9, 10.3,  9.8, 10. ,  9.7, 10.9, 10.9, 10. ,
        9.4, 10.4,  9. , 11. , 10.3,  9.9, 10.5, 10.6, 10.8, 10.6, 10.6,
       10.3,  9.5,  9.8, 11.2, 11.1, 10.3, 10. , 10.5, 10.6, 10.7, 10. ,
       10.6, 10.9, 10. , 10.3, 10.3,  9.7, 10.8, 11.1, 10.2,  9.5, 10.2,
       11.2, 10.5,  9.6,  9.7,  9.9, 10.7, 10. ,  9.5, 10.2, 10.3, 10.2,
       10. ])

In [8]:
X = features
y =labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state=42)

In [11]:
len(X_train)

67

In [12]:
len(X)

100

In [13]:
len(X_test)

33

In [14]:
y_test

array([10.8, 10.9, 11.1, 10.2, 10.2,  9.7, 10.8, 10.3, 11.7,  9.7, 11.5,
       10.7, 10.5, 10.3,  9.6,  7.7, 10. , 10.6, 10.8,  9.1,  9.4, 11.2,
        9.8,  9. , 11.2,  8.5,  9.4, 10.2, 10. , 10. , 10.5, 10.9, 10.2])

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [4]:
model  = Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [5]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])